// SPDX-FileCopyrightText: 2026 Anas
// SPDX-License-Identifier: AGPL-3.0-or-later

package com.privateai.camera.ui.passwords

import android.content.ClipData
import android.content.ClipboardManager
import android.content.Context
import android.os.Handler
import android.os.Looper
import android.widget.Toast
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.ContentCopy
import androidx.compose.material.icons.filled.Refresh
import androidx.compose.material3.Card
import androidx.compose.material3.CardDefaults
import androidx.compose.material3.Checkbox
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Slider
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableFloatStateOf
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import com.privateai.camera.R
import java.security.SecureRandom

/**
 * Inline password generator with length slider, character options, and copy.
 * The generated password is NOT stored — user copies it, pastes elsewhere,
 * then writes a hint to remember it.
 */
@Composable
fun PasswordGeneratorCard(modifier: Modifier = Modifier) {
    val context = LocalContext.current
    var length by remember { mutableFloatStateOf(16f) }
    var uppercase by remember { mutableStateOf(true) }
    var numbers by remember { mutableStateOf(true) }
    var symbols by remember { mutableStateOf(true) }
    var generated by remember { mutableStateOf(generatePassword(16, true, true, true)) }

    fun regenerate() {
        generated = generatePassword(length.toInt(), uppercase, numbers, symbols)
    }

    Card(
        modifier = modifier.fillMaxWidth(),
        shape = RoundedCornerShape(12.dp),
        colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surfaceVariant.copy(alpha = 0.5f))
    ) {
        Column(Modifier.padding(14.dp), verticalArrangement = Arrangement.spacedBy(8.dp)) {
            Text(
                stringResource(R.string.password_generator_title),
                style = MaterialTheme.typography.labelMedium,
                fontWeight = FontWeight.Bold,
                color = MaterialTheme.colorScheme.primary
            )

            // Generated password display
            Text(
                generated,
                style = MaterialTheme.typography.titleMedium,
                fontFamily = FontFamily.Monospace,
                color = MaterialTheme.colorScheme.onSurface,
                modifier = Modifier.fillMaxWidth()
            )

            // Length slider
            Row(
                Modifier.fillMaxWidth(),
                verticalAlignment = Alignment.CenterVertically,
                horizontalArrangement = Arrangement.spacedBy(8.dp)
            ) {
                Text("${length.toInt()}", style = MaterialTheme.typography.labelMedium, modifier = Modifier.size(28.dp))
                Slider(
                    value = length,
                    onValueChange = { length = it; regenerate() },
                    valueRange = 8f..32f,
                    steps = 23,
                    modifier = Modifier.weight(1f)
                )
            }

            // Options
            Row(
                Modifier.fillMaxWidth(),
                horizontalArrangement = Arrangement.spacedBy(12.dp)
            ) {
                Row(verticalAlignment = Alignment.CenterVertically) {
                    Checkbox(checked = uppercase, onCheckedChange = { uppercase = it; regenerate() })
                    Text("ABC", style = MaterialTheme.typography.labelSmall)
                }
                Row(verticalAlignment = Alignment.CenterVertically) {
                    Checkbox(checked = numbers, onCheckedChange = { numbers = it; regenerate() })
                    Text("123", style = MaterialTheme.typography.labelSmall)
                }
                Row(verticalAlignment = Alignment.CenterVertically) {
                    Checkbox(checked = symbols, onCheckedChange = { symbols = it; regenerate() })
                    Text("#!@", style = MaterialTheme.typography.labelSmall)
                }
            }

            // Actions
            Row(
                Modifier.fillMaxWidth(),
                horizontalArrangement = Arrangement.End,
                verticalAlignment = Alignment.CenterVertically
            ) {
                IconButton(onClick = { regenerate() }) {
                    Icon(Icons.Default.Refresh, stringResource(R.string.password_generator_new), Modifier.size(20.dp))
                }
                IconButton(onClick = { copyWithAutoClear(context, generated) }) {
                    Icon(Icons.Default.ContentCopy, stringResource(R.string.password_generator_copy), Modifier.size(20.dp), tint = MaterialTheme.colorScheme.primary)
                }
            }
        }
    }
}

/** Generate a cryptographically random password. */
fun generatePassword(
    length: Int = 16,
    uppercase: Boolean = true,
    numbers: Boolean = true,
    symbols: Boolean = true
): String {
    val chars = buildString {
        append("abcdefghijklmnopqrstuvwxyz")
        if (uppercase) append("ABCDEFGHIJKLMNOPQRSTUVWXYZ")
        if (numbers) append("0123456789")
        if (symbols) append("!@#\$%^&*()_+-=[]{}|;:,.<>?")
    }
    if (chars.isEmpty()) return ""
    val random = SecureRandom()
    return (1..length).map { chars[random.nextInt(chars.length)] }.joinToString("")
}

/**
 * Copy text to clipboard and auto-clear after 30 seconds.
 * Also shows a toast with the countdown.
 */
fun copyWithAutoClear(context: Context, text: String) {
    val cm = context.getSystemService(Context.CLIPBOARD_SERVICE) as ClipboardManager
    cm.setPrimaryClip(ClipData.newPlainText("password", text))
    Toast.makeText(context, context.getString(R.string.password_copied_auto_clear), Toast.LENGTH_LONG).show()

    // Auto-clear after 30 seconds
    Handler(Looper.getMainLooper()).postDelayed({
        try {
            cm.setPrimaryClip(ClipData.newPlainText("", ""))
        } catch (_: Exception) {}
    }, 30_000L)
}
